"""candidate and edits

Revision ID: 0a0dbee959f8
Revises: 
Create Date: 2019-04-02 12:44:40.337265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a0dbee959f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lang', mysql.TINYTEXT(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', mysql.TINYTEXT(), nullable=True),
    sa.Column('user_registration', sa.DateTime(), nullable=True),
    sa.Column('user_editcount', sa.Integer(), nullable=True),
    sa.Column('user_experience_level', mysql.TINYTEXT(), nullable=True),
    sa.Column('thanks_sent', sa.Integer(), nullable=True),
    sa.Column('thanks_received', sa.Integer(), nullable=True),
    sa.Column('has_email', sa.Boolean(), nullable=True),
    sa.Column('user_thanked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_candidates_created_at'), 'candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.create_table('edits',
    sa.Column('edit_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('lang', mysql.TINYTEXT(), nullable=True),
    sa.Column('rev_id', sa.Integer(), nullable=True),
    sa.Column('page_name', sa.TEXT(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('ores_damaging', sa.Boolean(), nullable=True),
    sa.Column('ores_goodfaith', sa.Boolean(), nullable=True),
    sa.Column('de_flagged', sa.Boolean(), nullable=True),
    sa.Column('de_flagged_algo_version', sa.Boolean(), nullable=True),
    sa.Column('edit_deleted', sa.NullType(), nullable=True),
    sa.Column('diffHTML', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('newRevId', sa.Integer(), nullable=True),
    sa.Column('newRevDate', mysql.TINYTEXT(), nullable=True),
    sa.Column('newRevUser', mysql.TINYTEXT(), nullable=True),
    sa.Column('newRevComment', sa.TEXT(), nullable=True),
    sa.Column('oldRevId', sa.Integer(), nullable=True),
    sa.Column('oldRevDate', mysql.TINYTEXT(), nullable=True),
    sa.Column('oldRevUser', mysql.TINYTEXT(), nullable=True),
    sa.Column('oldRevComment', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('edit_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edits')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_created_at'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
